<a href="https://colab.research.google.com/github/De-ORaCle/MAT251-Python-Team-Work/blob/main/Finite_Differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Working on the first table in the slide to find dy3 and dddy2

In [ ]:
x0 = float(input("x0= "))
x1 = float(input("x1= "))
x2 = float(input("x2= "))
x3 = float(input("x3= "))
x4 = float(input("x4= "))
x5 = float(input("x5= "))
x6 = float(input("x6= "))
x7 = float(input("x7= "))
x8 = float(input("x8= "))
x9 = float(input("x9= "))
x10 = float(input("x10= "))

In [ ]:
y0 = float(input("y0= "))
y1 = float(input("y1= "))
y2 = float(input("y2= "))
y3 = float(input("y3= "))
y4 = float(input("y4= "))
y5 = float(input("y5= "))
y6 = float(input("y6= "))
y7 = float(input("y7= "))
y8 = float(input("y8= "))
y9 = float(input("y9= "))
y10 = float(input("y10= "))

In [ ]:
dy = np.array([(y1-y0), (y2-y1), (y3-y2), (y4-y3), (y5-y4), (y6-y5), (y7-y6), (y8-y7), (y9-y8), (y10-y9)])
print(dy)


ddy = np.array([(dy[1]-dy[0]), (dy[2]-dy[1]), (dy[3]-dy[2]), (dy[4]-dy[3]), (dy[5]-dy[4]), (dy[6]-dy[5]), (dy[7]-dy[6]), (dy[8]-dy[7]), (dy[9]-dy[8])])
print(ddy)

dddy = np.array([(ddy[1]-ddy[0]), (ddy[2]-ddy[1]), (ddy[3]-ddy[2]), (ddy[4]-ddy[3]), (ddy[5]-ddy[4]), (ddy[6]-ddy[5]), (ddy[7]-ddy[6]), (ddy[8]-ddy[7])])
print(dddy)

ddddy = np.array([(dddy[1]-dddy[0]), (dddy[2]-dddy[1]), (dddy[3]-dddy[2]), (dddy[4]-dddy[3]), (dddy[5]-dddy[4]), (dddy[6]-dddy[5]), (dddy[7]-dddy[6])])
print(ddddy)

dddddy = np.array([(ddddy[1]-ddddy[0]), (ddddy[2]-ddddy[1]), (ddddy[3]-ddddy[2]), (ddddy[4]-ddddy[3]), (ddddy[5]-ddddy[4]), (ddddy[6]-ddddy[5])])
print(dddddy)

[0.5 0.4 0.7 0.5 0.7 0.7 0.5 0.6 0.6 0.8]
[-1.0000000e-01  3.0000000e-01 -2.0000000e-01  2.0000000e-01
  0.0000000e+00 -2.0000000e-01  1.0000000e-01  8.8817842e-16
  2.0000000e-01]
[ 0.4 -0.5  0.4 -0.2 -0.2  0.3 -0.1  0.2]
[-9.0000000e-01  9.0000000e-01 -6.0000000e-01  4.4408921e-16
  5.0000000e-01 -4.0000000e-01  3.0000000e-01]
[ 1.8 -1.5  0.6  0.5 -0.9  0.7]


In [ ]:
# Forward difference examples


In [ ]:
# stating_the_equation
# equation = input("State your equation in terms of x: ")